### ISSUE TITLE
Laravel Versions?

### ISSUE THREAD

**Issue by Jamesking56** [patricktalmadge/stripe#3]
Hello,

What version of Laravel does this work for?

I want to use this for Laravel 4 Beta but I'm not sure if this is for Laravel 3 only?

**Comment by patricktalmadge** [comment]
This stripe bundle was developed for Laravel 3. I haven't looked at upgrading it to Laravel 4 yet. If you would like to take up those changes and test I would be happy to merge them in.

**Comment by Jamesking56** [comment]
Since Laravel's creator made his own package for stripe called Laravel Cashier, this package seems to have died.
